name: Generate RULE-SET from OpenCCK Lists
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # 00:00 MSK = 21:00 UTC
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "opencck_anime=https://iplist.opencck.org/?format=text&data=domains&group=anime" >> $GITHUB_ENV
          echo "opencck_art=https://iplist.opencck.org/?format=text&data=domains&group=art" >> $GITHUB_ENV
          echo "opencck_games=https://iplist.opencck.org/?format=text&data=domains&group=games" >> $GITHUB_ENV
        shell: bash

      - name: Checkout the main branch
        uses: actions/checkout@v5

      - name: Generate anime.txt file
        run: |
          echo "payload:" > anime.txt
          curl -sSL ${opencck_anime} | grep -v '^#' | grep -v '^$' | while IFS= read -r domain; do
            if [[ $domain =~ ^www\. ]]; then
              echo "  - '${domain}'" >> anime.txt
              echo "  - '+.${domain#www.}'" >> anime.txt
            else
              echo "  - '+.${domain}'" >>anime.txt
            fi
          done

      - name: Generate art.txt file
        run: |
          echo "payload:" > art.txt
          curl -sSL ${opencck_art} | grep -v '^#' | grep -v '^$' | while IFS= read -r domain; do
            if [[ $domain =~ ^www\. ]]; then
              echo "  - '${domain}'" >> art.txt
              echo "  - '+.${domain#www.}'" >> art.txt
            else
              echo "  - '+.${domain}'" >> art.txt
            fi
          done

      - name: Generate games.txt file
        run: |
          echo "payload:" > games.txt
          curl -sSL ${opencck_games} | grep -v '^#' | grep -v '^$' | while IFS= read -r domain; do
            if [[ $domain =~ ^www\. ]]; then
              echo "  - '${domain}'" >> games.txt
              echo "  - '+.${domain#www.}'" >> games.txt
            else
              echo "  - '+.${domain}'" >> games.txt
            fi
          done  

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          cp *.txt ./publish/

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"

          done
